#!/usr/bin/env node
/**
 * Self-register a Fetch agent on the Locus beta.
 *
 * Usage:
 *   node scripts/bootstrap-locus.js [--name Fetch] [--email you@example.com] [--credits 10]
 *
 * Outputs a `.env.locus` file next to `.env` with the credentials. You then
 * source those values into your main `.env` (the script prints the exact lines
 * to paste).
 *
 * References:
 *   POST https://beta-api.paywithlocus.com/api/register
 *   POST https://beta-api.paywithlocus.com/api/gift-code-requests
 *   GET  https://beta-api.paywithlocus.com/api/status
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const orchestratorRoot = path.resolve(__dirname, '..');

const BETA_API = 'https://beta-api.paywithlocus.com/api';

function arg(name, fallback) {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx === -1) return fallback;
  return process.argv[idx + 1];
}

async function main() {
  const name = arg('name', 'Fetch');
  const email = arg('email', '');
  const creditsUsdc = Number(arg('credits', '10'));

  console.log(`Registering agent '${name}' on Locus beta…`);
  const regRes = await fetch(`${BETA_API}/register`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ name, ...(email ? { email } : {}) }),
  });
  if (!regRes.ok) {
    console.error(`register failed: ${regRes.status} ${await regRes.text()}`);
    process.exit(1);
  }
  const reg = await regRes.json();
  if (!reg.success) {
    console.error('register returned non-success:', reg);
    process.exit(1);
  }
  const d = reg.data;
  console.log('\n✓ Registered.');
  console.log(`  apiKey:          ${d.apiKey}`);
  console.log(`  ownerAddress:    ${d.ownerAddress}`);
  console.log(`  walletId:        ${d.walletId}`);
  console.log(`  walletStatus:    ${d.walletStatus}`);
  console.log(`  claimUrl:        ${d.claimUrl}`);
  console.log(`  defaults:        allowance=${d.defaults?.allowanceUsdc} USDC, maxTx=${d.defaults?.maxAllowedTxnSizeUsdc} USDC\n`);

  // Poll wallet status until deployed (best-effort, 60s max)
  console.log('Polling wallet deployment…');
  let walletAddress = null;
  for (let i = 0; i < 20; i += 1) {
    const s = await fetch(`${BETA_API}/status`, {
      headers: { authorization: `Bearer ${d.apiKey}` },
    }).then((r) => r.json()).catch(() => null);
    const status = s?.data?.status || s?.data?.walletStatus;
    walletAddress = s?.data?.walletAddress || s?.data?.address || walletAddress;
    process.stdout.write(`  [${i + 1}] status=${status || 'unknown'} address=${walletAddress || '—'}\r`);
    if (status === 'deployed' || walletAddress) break;
    await new Promise((r) => setTimeout(r, 3000));
  }
  console.log('');
  if (!walletAddress) {
    console.log('  (wallet still deploying — you can check later via /api/status)');
  } else {
    console.log(`✓ Wallet deployed at ${walletAddress}\n`);
  }

  // Request credits
  if (creditsUsdc > 0 && email) {
    console.log(`Requesting ${creditsUsdc} USDC in beta credits for ${email}…`);
    const credRes = await fetch(`${BETA_API}/gift-code-requests`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        email,
        reason: 'Building Fetch — agentic shopping on Locus for The Synthesis hackathon',
        requestedAmountUsdc: Math.min(creditsUsdc, 50),
      }),
    });
    const cred = await credRes.json().catch(() => ({}));
    if (credRes.ok && cred.success) {
      console.log('✓ Credits request submitted. Check your inbox for a redemption code.\n');
    } else {
      console.log(`  credit request: ${credRes.status} — ${cred.message || ''}`);
    }
  }

  // Persist credentials
  const outPath = path.join(orchestratorRoot, '.env.locus');
  const envBlob = [
    '# Generated by scripts/bootstrap-locus.js. Do not commit.',
    `LOCUS_MODE=real`,
    `LOCUS_API_KEY=${d.apiKey}`,
    `LOCUS_API_BASE=${BETA_API}`,
    `LOCUS_BUILD_API_BASE=https://api.buildwithlocus.com/v1`,
    `LOCUS_WALLET_ADDRESS=${walletAddress || ''}`,
    `LOCUS_OWNER_ADDRESS=${d.ownerAddress}`,
    `LOCUS_OWNER_PRIVATE_KEY=${d.ownerPrivateKey}`,
    `LOCUS_WALLET_ID=${d.walletId}`,
    `LOCUS_CLAIM_URL=${d.claimUrl}`,
    '',
  ].join('\n');
  fs.writeFileSync(outPath, envBlob);
  console.log(`Saved credentials to ${outPath}`);
  console.log('\nNext steps:');
  console.log('  1. Copy the lines above into your `.env` (or `cat .env.locus >> .env`).');
  console.log('  2. Open the claim URL in a browser to link this agent to a human dashboard account:');
  console.log(`        ${d.claimUrl}`);
  console.log('  3. Once credits land, fund the wallet and restart the orchestrator.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
